### PR TITLE
Update for play 2.5.x

### PR DESCRIPTION
**Pull request by kijuky**
# Summary

Update Play 2.5.x

# Detail

- update to 1.3
- fix readme
- fix Build.scala
- fix sample
  - fix controller 
  - add application.conf

| library | before | after | remarks |
|---|---|---|---|
| scala | 2.11.6, 2.10.5 | 2.11.8 | |
| sbt | 0.13.8 | 0.13.11 | |
| play | 2.4.0 | 2.5.19 | |

- I ran the following and confirmed that there is no problem.
  - sbt compile
  - sbt test
  - sbt "project sample" run

### CODE REVIEW

**Comment by lloydmeta** [comment]
Hey, thanks for this. I'll need to fix up a bunch of CI related things first before merging this, but it's on my todo.

**Comment by kijuky** [comment]
> I'll need to fix up a bunch of CI related things first before merging this

OK. I created a pull request #5 to resolve #4. I'll merge #5 into this pull request later.

**Comment by kijuky** [comment]
I merged #5 with this commit 88a8954ee

**Review by lloydmeta — APPROVED** [review]
LGTM

**Comment by lloydmeta** [comment]
@kijuky thanks for this. I just pushed 1.3 to maven central with these changes.

**Comment by kijuky** [comment]
Thank you for your work! It helped me a lot.

**Pull request merged**
